In [2]:
import numpy as np

In [12]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
x.shape

(3, 3)

In [6]:
z=np.array([[1,2,3],[4,5,6]])

In [7]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
z.shape

(2, 3)

In [15]:
z.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
z.min()

1

In [24]:
q=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [25]:
q.shape

(4, 3)

In [27]:
q.resize(3,4)

In [28]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
g=np.array([1,2,3,4], dtype=float)

In [30]:
g

array([1., 2., 3., 4.])

In [31]:
g.itemsize

8

In [32]:
g.size

4

In [38]:
v=np.arange(15)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
v.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
v.itemsize

4

In [41]:
v.size

15

In [42]:
v.data

In [43]:
m=np.arange(24)

In [44]:
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
m.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
ra=np.array([(34,78,89),(45,86,54)])

In [50]:
print(ra.ravel())

[34 78 89 45 86 54]


In [52]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [56]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [57]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a+b
print(c)

[20 31 42 53]


In [58]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [59]:
b=np.random.random((2,3))

In [60]:
b

array([[0.58011523, 0.41933161, 0.48268549],
       [0.41209939, 0.32731991, 0.56921519]])

In [61]:
c=np.ones((2,3))

In [62]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
d=b+c

In [64]:
d

array([[1.58011523, 1.41933161, 1.48268549],
       [1.41209939, 1.32731991, 1.56921519]])

In [65]:
B=np.arange(3)
B

array([0, 1, 2])

In [66]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [67]:
a=np.arange(10)

In [68]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a[2]

2

In [72]:
a[2:5]

array([2, 3, 4])

In [73]:
a[-1]

9

In [77]:
a[-5:-1]

array([5, 6, 7, 8])

In [78]:
a[-10:-6]

array([0, 1, 2, 3])

In [81]:
a[3:7]

array([3, 4, 5, 6])

In [82]:
d1=np.arange(20)

In [83]:
s=slice(2,20,2)

In [84]:
print(d1[s])

[ 2  4  6  8 10 12 14 16 18]


In [85]:
d2=np.arange(20)

In [88]:
d2[ :]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [89]:
d2[:5]

array([0, 1, 2, 3, 4])

In [90]:
d3=np.array([np.nan,1,2,3,np.nan,6,7,8])

In [91]:
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

In [93]:
print(d3[~np.isnan(d3)])

[1. 2. 3. 6. 7. 8.]


In [94]:
np.random.rand(2,2)

array([[0.81804175, 0.57450698],
       [0.63088562, 0.36066356]])

In [95]:
np.random.randn(2,3)

array([[-0.3412662 , -1.10834154, -0.96981801],
       [-0.46008073,  0.6102531 , -0.09528683]])

In [98]:
import pandas as pd
import numpy as np

In [5]:
import numpy as np
ndarray.ndim(10)

NameError: name 'ndarray' is not defined